version: '3'
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:3000"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
